### ISSUE TITLE
Face-to-face discussions needed?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-management#3]
@richared wrote:

> In general, we believe that architecture has to be discussed and agreed on face-to-face, as it is quite central for the whole project. It is too easy to forget or misunderstand things otherwise.

**Comment by wrygiel** [comment]
If we discuss something face-to-face only, then other partners won't know about what was discussed. I think we cannot rely on passing this kind of information face-to-face, we must have it written down, and every change to this information must be visible to all the partners.

Also, if we expect the EWP Network to expand after our work is finished, then such future partners might have trouble finding someone for face-to-face discussions.

**Comment by wrygiel** [comment]
@geirmv @mpuzar

**Comment by vickalaser** [comment]
I agree. It is very important to log everything associated with the project.
